definitions:
  dto.CreateGuestDTO:
    properties:
      email:
        type: string
      name:
        maxLength: 200
        minLength: 10
        type: string
      phone:
        type: string
    required:
    - email
    - name
    - phone
    type: object
  dto.CreateRoomDTO:
    properties:
      number:
        type: integer
      price_per_night:
        type: number
      type:
        type: string
    required:
    - number
    - price_per_night
    - type
    type: object
  dto.FindGuestDTO:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      phone:
        type: string
      reservations:
        items:
          $ref: '#/definitions/dto.FindReservationDTO'
        type: array
      updatedAt:
        type: string
    type: object
  dto.FindGuestInReservationDTO:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      phone:
        type: string
      updatedAt:
        type: string
    type: object
  dto.FindReservationDTO:
    properties:
      check_in:
        type: string
      check_out:
        type: string
      guest:
        $ref: '#/definitions/dto.FindGuestInReservationDTO'
      guest_id:
        type: string
      id:
        type: string
      room_id:
        type: string
      total_price:
        type: number
    type: object
  dto.FindRoomDTO:
    properties:
      id:
        type: string
      number:
        type: integer
      price_per_night:
        type: number
      reservations:
        items:
          $ref: '#/definitions/dto.FindReservationDTO'
        type: array
      type:
        type: string
    type: object
  handler.errorResponse:
    properties:
      error:
        type: string
    type: object
  handler.messageResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /guest/all:
    get:
      consumes:
      - application/json
      description: Find all guests
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.FindGuestDTO'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
      tags:
      - guests
  /guest/create:
    post:
      consumes:
      - application/json
      description: Create a new guest
      parameters:
      - description: Guest data
        in: body
        name: guest
        required: true
        schema:
          $ref: '#/definitions/dto.CreateGuestDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.messageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
      tags:
      - guests
  /guest/delete/{id}:
    delete:
      consumes:
      - application/json
      description: delete guest
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.messageResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
      tags:
      - guests
  /guest/update/{id}:
    put:
      consumes:
      - application/json
      description: update guest
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.messageResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
      tags:
      - guests
  /room/{id}:
    get:
      consumes:
      - application/json
      description: find one room by id
      parameters:
      - description: room id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.FindRoomDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
      tags:
      - rooms
  /room/all:
    get:
      consumes:
      - application/json
      description: find all rooms
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/dto.FindRoomDTO'
              type: array
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
      tags:
      - rooms
  /room/create:
    post:
      consumes:
      - application/json
      description: Create a new hotel room
      parameters:
      - description: Room data
        in: body
        name: room
        required: true
        schema:
          $ref: '#/definitions/dto.CreateRoomDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.messageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
      tags:
      - rooms
  /room/delete/{id}:
    delete:
      consumes:
      - application/json
      description: delete room by id
      parameters:
      - description: room id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.messageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
      tags:
      - rooms
  /room/update/{id}:
    put:
      consumes:
      - application/json
      description: update room by id
      parameters:
      - description: room id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.messageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
      tags:
      - rooms
swagger: "2.0"
